# vim: set ft=yaml ts=2 expandtab:
---

- name: epel is present
  include_role:
    name: mafalb.epel.release
    allow_duplicates: no
  when: tor_relay_needs_epel|default(false)

- name: tor relay is installed
  package:
    name: tor

...
