# vim: set ft=yaml ts=2 expandtab:
---

- name: epel is present
  package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
  when: tor_relay_needs_epel|default(false)

- name: tor relay is installed
  package:
    name: tor

...
