# vim: set ft=yaml ts=2 expandtab:
---

- name: converge tor
  hosts: all,!infrastructure_group

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  roles:

  - role: mafalb.tor.relay

...
